name = "fmmap"
version = "0.11.2"
license = "GPL-3.0-only"
author = "Pierre Hugonnet"
maintainer = "Pierre Hugonnet"
copyright = "Copyright 2024, Pierre Hugonnet"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = true
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
