name = "fmmap"
version = "0.10.2"
license = "GPL 3"
author = "Pierre Hugonnet"
maintainer = "Pierre Hugonnet"
copyright = "Copyright 2024, Pierre Hugonnet"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

